### ISSUE TITLE
AST Transforms

### ISSUE THREAD

**Issue by chadbrewbaker** [palatable/lambda#12]
Would it be useful to have some clang-format style AST transforms that rewrite code in a functional style?

Which AST rewriter is the most robust for Java? Jetbrains Community libraries, one of the Apache projects, ANTLR?

**Comment by jnape** [comment]
Hi Chad --

> Would it be useful to have some clang-format style AST transforms that rewrite code in a functional style?

Almost certainly, although I suspect anything valuable in this space would probably demand its own artifact (perhaps lambda-ast-extras or something). One particularly low-hanging fruit I'd like for this sort of thing would be poor-man's TC -> loop rewriting. 

What were you thinking?

> Which AST rewriter is the most robust for Java? Jetbrains Community libraries, one of the Apache projects, ANTLR?

I'm not really hip to the current landscape of AST rewriters, so, you're guess is as good as mine; but I certainly hope there are better options these days than ANTLR. A solid AST library that was completely decoupled from grammar or byte-code parsing/generation has actually been on my todo list for a few years; if only I could find the time.

The Jetbrains folks generally produce reasonable things; I'd probably try to see what they use for IntelliJ.

**Comment by jnape** [comment]
Closing, as this questions seems to be dead in the water.
