### ISSUE TITLE
Pattern Matching

### ISSUE THREAD

**Issue by jnape** [palatable/lambda#21]
A reasonable encoding of value-level pattern matching may be achievable/desirable.

- partial and total matches type check
- destructuring logic should be supplementary to value types, not part of the class definition. This also means there can be multiple ways to destructure the same value type, decidable at match time
- reasonable default match combinators with seamless integration with current Predicate type hierarchy

**Comment by jnape** [comment]
Tracking this work on the [structuralmatching](https://github.com/palatable/lambda/tree/structuralmatching) branch.

**Comment by ssijak** [comment]
Pattern matching is coming to Java, maybe even in version 12.
http://openjdk.java.net/jeps/305
http://openjdk.java.net/jeps/325

**Comment by jnape** [comment]
Hi @ssijak, and thanks for the comment.

Yes, I've read the proposals, and while I'm skeptical of how much will make it into the recent upcoming JDKs (and how buggy it will be), they seem like they'll be vast improvements over the current lay of the land in Java. I've actually held off on finalizing the pattern matching branch and merging it to master because I'm interested in seeing where this whole thing goes first.

Surprisingly, they're offering an exhaustive expression form of a switch statement. That rocks.

Unsurprisingly, the switch expression itself is not represented as a type (the result of a switch expression has a type, the unevaluated switch expression does not). That does not rock. That is neither composable nor portable. Certainly one could return Supplier or some such out of the switch expression, but that still leaves the problem of deferring precisely *what* value should be switched on and encapsulating the logic in the cases immediately (think of passing a Function<? super T, ? extends R> where T is the what should be switched on and R is the result).

Finally, there's the matter of rich destructuring: not just of a nested value, but being able to compose and apply a guard clause (or predicate) to the destructured value before matching. This is really the goal I'm getting at with my pattern matching branch (as well as exhaustivity, which it looks like expression switch statements will support, great!). It seems like this could in the best case be touched on briefly; again, I am interested in seeing where this goes.

Thanks again for the heads up, and for all of our sakes, I hope they nail pattern matching with a language feature. I'd love to feel like there was less that Java was desperately missing that was left to the community to try to anemically add via 3rd party libraries like Lambda and herculean efforts for marginal payout.

**Comment by jnape** [comment]
I'll take this off the table for now, if it becomes I highly desired library feature, I'll resurrect it.
