### ISSUE TITLE
99 Lisp Problems sub-site for lambda

### ISSUE THREAD

**Issue by jnape** [palatable/lambda#52]
It would probably be pretty compelling to see the 99 lisp problems (https://www.ic.unicamp.br/~meidanis/courses/mc336/2006s2/funcional/L-99_Ninety-Nine_Lisp_Problems.html) solved with lambda solutions.

**Comment by 7h3kk1d** [comment]
I added https://github.com/7h3kk1d/ninetynineylambdas. Going to do some of the implementations over the weekend. Trying to change the requirements to provide total functions by using Maybe and the like.

**Comment by jnape** [comment]
Closing, as @7h3kk1d has picked this up in a separate repo. Thanks @7h3kk1d!
