### ISSUE TITLE
Add LTWith, GTWith, etc.

### ISSUE THREAD

**Issue by jnape** [palatable/lambda#77]
`LTBy`, `GTBy`, and friends all expect to be able to map `A -> B` where `B extends Comparable<B>>`, which is fine, but does nothing for cases where there is no sensible target that extends `Comparable` to use for comparison.

In these cases, simply providing a `Comparator<A>` is preferential. Furthermore, the `Comparator<A>` case generalizes the mapping case via `Comparator#comparing`.

All the `By` variants may be worth keeping around for convenience, but there should at least exist the following `With` variants taking `Comparator`:

- `LTWith`
- `LTEWith`
- `CmpEqWith`
- `GTWith`
- `GTEWith`
- `MinWith`
- `MaxWith`

**Comment by 7h3kk1d** [comment]
Pull request submitted

**Comment by jnape** [comment]
Added in 994afb1
