### ISSUE TITLE
Review kraftwerk for community section

### ISSUE THREAD

**Issue by kschuetz** [palatable/lambda#98]
[kraftwerk](https://github.com/kschuetz/kraftwerk) is the library that [gauntlet](https://github.com/kschuetz/gauntlet) uses for sample generation.  It is meant to be a general purpose generator/combinator library that can be also used for applications other than property-testing.  At this point, kraftwerk is usable and can be considered of beta-quality.  Please consider reviewing it and adding it to your community section.

**Comment by jnape** [comment]
@kschuetz Can you add it to the README and PR it in?

**Comment by jnape** [comment]
Closed by #107
